# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

# disable until https://github.com/Lightning-AI/pytorch-lightning/pull/21016 is included in a release
# rich_progress_bar:
#   _target_: lightning.pytorch.callbacks.RichProgressBar
